nodeLinker: pnp

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"

pnpMode: loose

packageExtensions:
  debug@*:
    dependencies:
      supports-color: "*"
