name: Build and Publish Pact Tests

on:
  push:
    branches: [main]

jobs:
  pact-publish-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      # - name: Build Consumer Pact Tests
      #   run: |
      #     cd packages
      #     cd twitter-ui
      #     yarn install
      #     yarn run test:pact
      # - name: Build Provider Pact Tests
      #   run: |
      #     cd packages
      #     cd mock-service
      #     yarn install
      #     yarn run test:pact
